-- ============================================================
-- MSV Invoice Service — Initial Database Schema
-- Migration : V1__init_schema.sql
-- Database  : MySQL 8.0+
-- Charset   : utf8mb4 (full Unicode + emoji support)
-- ============================================================

-- ── Customers ─────────────────────────────────────────────────────
-- CREATE TABLE customers (
--     id              BIGINT          NOT NULL AUTO_INCREMENT,
--     merchant_id     BIGINT          NOT NULL,
--     customer_uuid   VARCHAR(36)     NOT NULL,
--     name            VARCHAR(255)    NOT NULL,
--     email           VARCHAR(255),
--     phone           VARCHAR(20),
--     address         TEXT,
--     company_name    VARCHAR(255),
--     tax_id          VARCHAR(100),
--     is_active       TINYINT(1)      NOT NULL DEFAULT 1,
--
--     -- Audit
--     created_at    DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
--     updated_at    DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
--     created_by    VARCHAR(100),
--     updated_by    VARCHAR(100),
--
--     PRIMARY KEY (id),
--     UNIQUE KEY uk_customers_uuid         (customer_uuid),
--     KEY idx_customers_merchant_id        (merchant_id),
--     KEY idx_customers_email              (email),
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
--   COMMENT='Customer billing contacts';